# Detekt configuration for Android Interval Shuffter
# https://detekt.dev/docs/rules/

build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true

complexity:
  LongMethod:
    threshold: 60
    ignoreAnnotated: ['Composable']
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    thresholdInFiles: 25
    thresholdInClasses: 25
    thresholdInInterfaces: 10
    thresholdInObjects: 15
    thresholdInEnums: 10
  ComplexCondition:
    threshold: 5
  CyclomaticComplexMethod:
    threshold: 20

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludes: ['**/test/**', '**/androidTest/**']
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][A-Za-z0-9]*'
  PackageNaming:
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: true
  UnusedPrivateMember:
    active: true
  ReturnCount:
    max: 4
  ForbiddenComment:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    ignoreOverridden: true

exceptions:
  TooGenericExceptionCaught:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'

potential-bugs:
  UnsafeCast:
    active: true
